In [28]:
# import dependencies
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [29]:
# Load the csv file and display the data
tweet_data = pd.read_csv("resources/covidvaccine.csv")
tweet_data

C:\ProgramData\Anaconda3\envs\P36\lib\site-packages\IPython\core\interactiveshell.py:3072: DtypeWarning: Columns (5,6,7,12) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,user_name,user_location,user_description,user_created,user_followers,user_friends,user_favourites,user_verified,date,text,hashtags,source,is_retweet
0,MyNewsNE,Assam,MyNewsNE a dedicated multi-lingual media house...,24-05-2020 10:18,64.0,11.0,110.0,False,18-08-2020 12:55,Australia to Manufacture Covid-19 Vaccine and ...,['CovidVaccine'],Twitter Web App,False
1,Shubham Gupta,NaN,I will tell about all experiences of my life f...,14-08-2020 16:42,1.0,17.0,0.0,False,18-08-2020 12:55,#CoronavirusVaccine #CoronaVaccine #CovidVacci...,"['CoronavirusVaccine', 'CoronaVaccine', 'Covid...",Twitter for Android,False
2,Journal of Infectiology,NaN,Journal of Infectiology (ISSN 2689-9981) is ac...,14-12-2017 07:07,143.0,566.0,8.0,False,18-08-2020 12:46,Deaths due to COVID-19 in Affected Countries\n...,NaN,Twitter Web App,False
3,Zane,NaN,Fresher than you.,18-09-2019 11:01,29.0,25.0,620.0,False,18-08-2020 12:45,@Team_Subhashree @subhashreesotwe @iamrajchoco...,NaN,Twitter for Android,False
4,Ann-Maree O’Connor,"Adelaide, South Australia",Retired university administrator. Melburnian b...,24-01-2013 14:53,83.0,497.0,10737.0,False,18-08-2020 12:45,@michellegrattan @ConversationEDU This is what...,NaN,Twitter Web App,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
156491,Andreas Rechkemmer,"Doha, Qatar",Professor of Global Policy and Founding Direct...,2016-04-08 14:59:19,130.0,427,60,False,2021-03-04 12:19:06,Very good news about the efficacy of the J&amp...,"['COVID19', 'COVIDVaccination', 'CovidVaccine']",Twitter for iPhone,False
156492,Dr. Akbar Niazi Teaching Hospital,NaN,Dr. Akbar Niazi Teaching Hospital (ANTH) is a ...,2019-03-24 07:32:27,83.0,9,1,False,2021-03-04 12:18:55,🇨🇳's Foreign Minister Wang Yi has also said th...,NaN,Twitter Web App,False
156493,Bnar Talabani,UK,@gw4_cat Wellcome Trust Fellow. Clinical Acade...,2009-03-11 17:32:39,327.0,909,593,False,2021-03-04 12:18:54,Super excited to have received my second #covi...,['covidvaccine'],Twitter for iPhone,False
156494,Sophia,NaN,'One day the war will end and I will resume my...,2010-06-02 02:04:42,6688.0,2744,64605,False,2021-03-04 12:18:39,"Repeat after me, Canadians are polite, they wo...",['Trudeau'],Twitter Web App,False
156495,Tahir Saeed,Pakistan,My thoughts... that might change or not with t...,2018-08-23 13:29:03,0.0,4,0,False,2021-03-04 12:17:01,Instead of postponing psl why not vaccinate al...,"['PSLPostponed', 'PSL6', 'CovidVaccine']",Twitter for Android,False

In [7]:
# Display the data information
tweet_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 156496 entries, 0 to 156495
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   user_name         156492 non-null  object
 1   user_location     124634 non-null  object
 2   user_description  147600 non-null  object
 3   user_created      156492 non-null  object
 4   user_followers    156491 non-null  float64
 5   user_friends      156491 non-null  object
 6   user_favourites   156491 non-null  object
 7   user_verified     156491 non-null  object
 8   date              156490 non-null  object
 9   text              156491 non-null  object
 10  hashtags          106430 non-null  object
 11  source            156348 non-null  object
 12  is_retweet        156486 non-null  object
dtypes: float64(1), object(12)
memory usage: 15.5+ MB

In [30]:
# Filter the records with null user name 
tweet_data[tweet_data['user_name'].isnull()]

,user_name,user_location,user_description,user_created,user_followers,user_friends,user_favourites,user_verified,date,text,hashtags,source,is_retweet
51425,NaN,NaN,@PelosiLovesDJT's account is temporarily unava...,2021-01-10 04:52:08,90.0,36,37,False,2021-01-12 04:17:00,@PelosiLovesDJT's account is temporarily unava...,NaN,Twitter for Android,False
121242,NaN,NaN,@farrahraja's account has been withheld in Ind...,2015-08-22 22:43:18,4989.0,1482,145584,False,2021-02-06 11:41:46,@farrahraja's account has been withheld in Ind...,NaN,Twitter for Android,False
140102,NaN,NaN,@EngrMuhammadQa9's account has been withheld i...,2020-11-03 09:16:01,6.0,79,2528,False,2021-02-24 12:41:52,@EngrMuhammadQa9's account has been withheld i...,NaN,Twitter for Android,False
151183,NaN,NaN,@furqanraja1122's account has been withheld in...,2015-10-06 11:25:25,2224.0,2816,3591,False,2021-02-28 14:36:18,@furqanraja1122's account has been withheld in...,NaN,Twitter Web App,False

The description shows that the user accounts have been withheld and no tweets are available in these records. So these records can be deleted

In [33]:
# Delete records with null user name
tweet_data.drop(tweet_data[tweet_data['user_name'].isnull()].index, inplace=True)

In [34]:
# Check if the null usernames are deleted
tweet_data[tweet_data['user_name'].isnull()]

Empty DataFrame
Columns: [user_name, user_location, user_description, user_created, user_followers, user_friends, user_favourites, user_verified, date, text, hashtags, source, is_retweet]
Index: []

In [35]:
tweet_data[tweet_data['user_location'].isnull()]

,user_name,user_location,user_description,user_created,user_followers,user_friends,user_favourites,user_verified,date,text,hashtags,source,is_retweet
1,Shubham Gupta,NaN,I will tell about all experiences of my life f...,14-08-2020 16:42,1.0,17.0,0.0,False,18-08-2020 12:55,#CoronavirusVaccine #CoronaVaccine #CovidVacci...,"['CoronavirusVaccine', 'CoronaVaccine', 'Covid...",Twitter for Android,False
2,Journal of Infectiology,NaN,Journal of Infectiology (ISSN 2689-9981) is ac...,14-12-2017 07:07,143.0,566.0,8.0,False,18-08-2020 12:46,Deaths due to COVID-19 in Affected Countries\n...,NaN,Twitter Web App,False
3,Zane,NaN,Fresher than you.,18-09-2019 11:01,29.0,25.0,620.0,False,18-08-2020 12:45,@Team_Subhashree @subhashreesotwe @iamrajchoco...,NaN,Twitter for Android,False
5,Raunak Scherbatsky DankWorth,NaN,Neuro surgeon + Diagnostician.👨‍⚕️\na good phy...,03-08-2020 13:39,3.0,27.0,918.0,False,18-08-2020 12:44,The Multi-system Inflammatory Syndrome-Childre...,"['COVID19', 'COVID19India']",Twitter for Android,False
14,Live sport is back!,NaN,Sport is the elixir of life!,31-03-2009 08:14,147.0,351.0,482.0,False,18-08-2020 10:39,The whole narrative on the #CovidVaccine has g...,"['CovidVaccine', 'ChinaVirus', 'COVID19India']",Twitter Web App,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
156481,Dr. Akbar Niazi Teaching Hospital,NaN,Dr. Akbar Niazi Teaching Hospital (ANTH) is a ...,2019-03-24 07:32:27,83.0,9,1,False,2021-03-04 12:20:07,A sad incident took place in #Japan🇯🇵. Accordi...,['Japan'],Twitter Web App,False
156486,Dr. Akbar Niazi Teaching Hospital,NaN,Dr. Akbar Niazi Teaching Hospital (ANTH) is a ...,2019-03-24 07:32:27,83.0,9,1,False,2021-03-04 12:19:45,Necessary efforts have been made to raise mass...,NaN,Twitter Web App,False
156490,Dr. Akbar Niazi Teaching Hospital,NaN,Dr. Akbar Niazi Teaching Hospital (ANTH) is a ...,2019-03-24 07:32:27,83.0,9,1,False,2021-03-04 12:19:15,Parliamentary Health Secretary Dr. Nausheen Ha...,NaN,Twitter Web App,False
156492,Dr. Akbar Niazi Teaching Hospital,NaN,Dr. Akbar Niazi Teaching Hospital (ANTH) is a ...,2019-03-24 07:32:27,83.0,9,1,False,2021-03-04 12:18:55,🇨🇳's Foreign Minister Wang Yi has also said th...,NaN,Twitter Web App,False
156494,Sophia,NaN,'One day the war will end and I will resume my...,2010-06-02 02:04:42,6688.0,2744,64605,False,2021-03-04 12:18:39,"Repeat after me, Canadians are polite, they wo...",['Trudeau'],Twitter Web App,False

In [36]:
tweet_data['user_location'].unique()

array(['Assam', nan, 'Adelaide, South Australia', ...,
       'Preet Vihar, New Delhi', 'Muzafrabad JK AKHAND BHARAT',
       'Statesville, NC'], dtype=object)

In [37]:
tweet_data[tweet_data['user_location'] == '...']

,user_name,user_location,user_description,user_created,user_followers,user_friends,user_favourites,user_verified,date,text,hashtags,source,is_retweet
25785,CRD,...,Poet/Pianist/Politics/Art& #BB Commentary Wome...,2009-08-27 02:30:28,4290.0,4631.0,54263.0,False,2020-12-31 00:32:15,"Of course. This country under #Trump, and his...",['Trump'],Twitter for iPad,False
139334,gaius odiase,...,NaN,2014-12-22 21:55:46,3116.0,2920,839,False,2021-02-24 17:49:19,but why is 🇬🇭 getting #covidvaccine before 🇳🇬..?,['covidvaccine'],Twitter for Android,False
155217,CRD,...,Poet/Pianist/Politics/Art& #BB Commentary Wome...,2009-08-27 02:30:28,4293.0,4336,55569,False,2021-03-04 19:51:57,Really seems like some Republican Govs R tryin...,NaN,Twitter for Android,False